clients/pricing-client/src/openapi.json

Update pricing client types to handle new address fields available for order creation.

feat: Update Pricing Client Types To Handle New Address Fields

---

clients/pricing-client/src/openapi.d.ts
clients/pricing-client/src/openapi.json

Update Price Client Types

---

README.md

Provides better documentation on how to update the client SDKs from new API specs.
> -- w/ 💙 from Sintra ⛰️

chore(docs): publish documentation

---

clients/entity-client/src/openapi.d.ts
clients/entity-client/src/openapi.json

Renaming the `setting` to `setting_flag`

fix: Update setting to setting_flag

---

clients/pricing-client/src/openapi.d.ts
clients/pricing-client/src/openapi.json

1. Add Relations to orders;
2. on_request_approved property to PriceItem

feat: Add Relations to orders + on_request_approved property to PriceItem

---

clients/workflow-definition-client/CHANGELOG.md
clients/workflow-definition-client/README.md
clients/workflow-definition-client/jest.config.ts
clients/workflow-definition-client/package-lock.json
clients/workflow-definition-client/package.json
clients/workflow-definition-client/src/client.test.ts
clients/workflow-definition-client/src/client.ts
clients/workflow-definition-client/src/definition.ts
clients/workflow-definition-client/src/index.ts
clients/workflow-definition-client/src/openapi.d.ts
clients/workflow-definition-client/src/openapi.json
clients/workflow-definition-client/tsconfig.json
clients/workflow-definition-client/webpack.config.js

New Workflow Definition Client

feat: add new Wf Def client

---

clients/pricing-client/src/openapi.d.ts
clients/pricing-client/src/openapi.json

This change comes to support the new Dynamic Price feature.

Feat: Add new PriceInputMappings type + update price Dtos

---

clients/entity-client/src/openapi.d.ts
clients/entity-client/src/openapi.json

1) Add description to relation_affinity_mode;
2) Remove delete_mode - Not used

Entity Client - Update Attributes

---

clients/automation-client/package-lock.json
clients/discussion-client/package-lock.json
clients/email-settings-client/package-lock.json
clients/email-template-client/package-lock.json
clients/entity-mapping-client/package-lock.json
clients/file-client/package-lock.json
clients/message-client/package-lock.json
clients/notification-client/package-lock.json
clients/partner-directory-client/package-lock.json
clients/permissions-client/package-lock.json
clients/pricing-client/package-lock.json
clients/pricing-client/src/openapi.d.ts
clients/pricing-client/src/openapi.json
clients/submission-client/package-lock.json
clients/template-variables-client/package-lock.json
clients/user-client/package-lock.json
clients/webhooks-client/package-lock.json
clients/workflow-client/package-lock.json
clients/workflow-definition-client/package-lock.json
packages/epilot-sdk/package-lock.json

Support volume pricing in pricing-lib.

Feat: Add support for volume pricing

---

clients/pricing-client/src/openapi.d.ts
clients/pricing-client/src/openapi.json

Support on_request_approved on composite prices.

Feat: Support on_request_approved on composite prices

---

clients/address-suggestions-client/.gitignore
clients/address-suggestions-client/README.md
clients/address-suggestions-client/jest.config.ts
clients/address-suggestions-client/package-lock.json
clients/address-suggestions-client/package.json
clients/address-suggestions-client/src/client.test.ts
clients/address-suggestions-client/src/client.ts
clients/address-suggestions-client/src/definition.ts
clients/address-suggestions-client/src/index.ts
clients/address-suggestions-client/src/openapi-runtime.json
clients/address-suggestions-client/src/openapi.d.ts
clients/address-suggestions-client/src/openapi.json
clients/address-suggestions-client/tsconfig.json
clients/address-suggestions-client/webpack.config.js
packages/epilot-sdk/package.json
packages/epilot-sdk/src/address-suggestions-client.ts
packages/epilot-sdk/src/index.ts

Adds new client for Address Suggestions API

feat: new client for address-suggestions

---

clients/file-client/package.json
clients/file-client/src/openapi-runtime.json
clients/file-client/src/openapi.d.ts
clients/file-client/src/openapi.json

* Endpoint for bulk downloads
* Endpoint for public file previews
* Bump version

File Client:

---

clients/entity-client/package.json

remove local path parameter of typegen

chore: correct entity-client path

---

clients/pricing-client/src/openapi.d.ts
clients/pricing-client/src/openapi.json

This MR is linked to [STABLE360-4076](https://e-pilot.atlassian.net/browse/STABLE360-4076). Adds total amount and sub-total amount with full precision to the spec.

feat: adds types for total and sub-total amounts with full precision

---

clients/document-client/src/openapi.json

Harmonizes the different kinds of error types and codes returned from the API.

chore: improves document-client types

---

clients/user-client/package-lock.json
clients/user-client/package.json
clients/user-client/src/openapi.d.ts
clients/user-client/src/openapi.json

Add override_release_channel option to user-client

---

clients/automation-client/package-lock.json
clients/billing-client/package-lock.json
clients/consent-client/package-lock.json
clients/email-settings-client/package-lock.json
clients/entity-client/package-lock.json
clients/file-client/package-lock.json
clients/file-client/package.json
clients/file-client/src/openapi-runtime.json
clients/file-client/src/openapi.d.ts
clients/file-client/src/openapi.json
clients/message-client/package-lock.json
clients/metering-client/package-lock.json
clients/partner-directory-client/package-lock.json
clients/permissions-client/package-lock.json
clients/tf-blueprints-client/package-lock.json
clients/user-client/package-lock.json
clients/workflow-client/package-lock.json
packages/epilot-sdk/package-lock.json
packages/epilot-sdk/package.json

Also bumps client version from 1.10.0 to 1.11.0

Upgrades `file-client` to contain new specs

---

clients/blueprint-manifest-client/package.json
clients/blueprint-manifest-client/src/openapi.d.ts

- Adds new Manifest API endpoints to the client, namely: getManifest, deleteManifest, listInstalledManifests

Update blueprint manifest client

---

clients/consent-client/src/index.ts
clients/entity-mapping-client/src/index.ts
clients/file-client/src/index.ts
clients/organization-client/src/index.ts
clients/permissions-client/src/index.ts
clients/pricing-client/src/index.ts
clients/pricing-tier-client/src/index.ts
clients/submission-client/src/index.ts
clients/template-variables-client/src/openapi.d.ts
clients/template-variables-client/src/openapi.json
clients/webhooks-client/src/index.ts
clients/workflow-client/src/index.ts
clients/workflow-definition-client/src/index.ts

Adds support for new variables of type `journey_link`.

Adds new variable type to the `template-variables-client`

---

clients/message-client/package.json
clients/message-client/src/openapi-runtime.json
clients/message-client/src/openapi.json

Adds new endpoint to the messaging api

chore: update message client

---

clients/entity-client/package-lock.json
clients/entity-client/package.json
clients/entity-client/src/openapi-runtime.json
clients/entity-client/src/openapi.d.ts
clients/entity-client/src/openapi.json

feat.getrelationsv3-with-filter-for-fields

---

clients/blueprint-manifest-client/package-lock.json
clients/blueprint-manifest-client/package.json
clients/organization-client/package.json
clients/organization-client/src/openapi.d.ts
clients/organization-client/src/openapi.json

Update organization client with parent_production_org_id

Update organization client with parent_production_org_id

---

clients/blueprint-manifest-client/package-lock.json
clients/blueprint-manifest-client/package.json
clients/blueprint-manifest-client/src/openapi.d.ts
clients/blueprint-manifest-client/src/openapi.json

manifest-api PR: https://gitlab.com/e-pilot/product/blueprints/blueprint-manifest-api/-/merge_requests/215
blueprints PR: https://gitlab.com/e-pilot/product/360-portal/epilot360-blueprints/-/merge_requests/119

feat: implements ready state resources

---

clients/kanban-client/package-lock.json
clients/kanban-client/package.json
clients/kanban-client/src/openapi.d.ts
clients/kanban-client/src/openapi.json

git commit -am 'chore(kanban-client): update client with new specs for card config
